### ISSUE TITLE
Error on Player Leave

### ISSUE THREAD

**Issue by ZandercraftGames** [Arthed-Plugins/Crawling#1]
The following error occurs when a player leaves the server. So far it does not seem to cause any issues, but nonetheless should be fixed.

```
[18:20:48 ERROR]: Could not pass event PlayerQuitEvent to Crawling v5.1.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.scheduler.BukkitTask.cancel()" because "this.updateTask" is null
        at me.arthed.crawling.players.CrPlayer.stopCrawling(CrPlayer.java:127) ~[Crawling-5.1.0.jar:?]
        at me.arthed.crawling.players.PlayerManager.onPlayerQuit(PlayerManager.java:35) ~[Crawling-5.1.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor276.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1331]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1331]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1331]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1331]
        at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:610) ~[patched_1.17.1.jar:git-Purpur-1331]
        at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:593) ~[patched_1.17.1.jar:git-Purpur-1331]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2014) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1994) ~[app:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:743) ~[app:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:221) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1659) ~[patched_1.17.1.jar:git-Purpur-1331]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1331]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1331]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1331]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1331]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[18:20:48 INFO]: MurrayElliot left the game
```

**Comment by Styro457** [comment]
Fixed
